name: Deploy Automatico Proddyt Labs

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Executar Deploy via SSH na TV Box
        uses: appleboy/ssh-action@master
        with:
          host: tvbox.proddyt.com   # Endereço público que passa pelo Cloudflare Tunnel
          username: proddyt         # O seu usuário lá na TV Box (visto no terminal: proddyt@rk322x-box)
          port: 22                  # Porta padrão do SSH
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Aquela chave privada gigante que você salvou nos Secrets
          script: |
            cd /var/www/html
            git pull origin main
